spring:
  datasource:
    initialization-mode: always
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/courier
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /doc/swagger-ui.html
    operationsSorter: method

server:
    servlet:
      context-path: /api/v1/courier

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full
  hystrix:
    enabled: true

core:
  deliveriesApi:
    url: https://core_url/deliveries

client:
  deliveriesApi:
    url: https://client_url/deliveries

# <sec> <min> <hour> <day-of-month> <month> <day-of-week>
cron:
  expression: 0 0 9-20 * * MON-FRI #every hour from 9:00 to 20:00 from monday to friday